import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const tracks = [
  {
    title: "Midnight Rain",
    artist: "Chillhop Producer",
    genre: "lofi-hiphop",
    mood: "melancholic",
    tempo: "slow",
    instrument: "piano",
    durationSec: 197,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/chillhop-producer/midnight-rain",
    sourcePlatform: "SoundCloud",
    tags: "rain,melancholy,night,piano",
    isYoutubeSafe: true,
  },
  {
    title: "Coffee Shop Dreams",
    artist: "LoFi Master",
    genre: "lofi-chill",
    mood: "cozy",
    tempo: "medium",
    instrument: "mixed",
    durationSec: 224,
    licenseType: "CC-BY-3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://freemusicarchive.org/music/lofi-master/coffee-shop-dreams/",
    sourcePlatform: "FMA",
    tags: "coffee,cozy,warm,cafe",
    isYoutubeSafe: true,
  },
  {
    title: "Vinyl Crackle",
    artist: "Ambient Waves",
    genre: "lofi-ambient",
    mood: "nostalgic",
    tempo: "slow",
    instrument: "synth",
    durationSec: 263,
    licenseType: "Pixabay",
    licenseUrl: "https://pixabay.com/service/terms/",
    sourceUrl: "https://pixabay.com/music/ambient-waves-vinyl-crackle/",
    sourcePlatform: "Pixabay",
    tags: "vinyl,crackle,nostalgia,ambience",
    isYoutubeSafe: true,
  },
  {
    title: "Study Session",
    artist: "BeatsForStudy",
    genre: "lofi-study",
    mood: "focused",
    tempo: "medium",
    instrument: "piano",
    durationSec: 188,
    licenseType: "CC-BY-SA",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/beatsforstudy/study-session/",
    sourcePlatform: "FMA",
    tags: "study,focus,concentration,piano",
    isYoutubeSafe: true,
  },
  {
    title: "Rainy Window",
    artist: "NostalgicBeats",
    genre: "lofi-hiphop",
    mood: "nostalgic",
    tempo: "slow",
    instrument: "drums",
    durationSec: 210,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/nostalgicbeats/rainy-window",
    sourcePlatform: "SoundCloud",
    tags: "rain,window,nostalgia,beats",
    isYoutubeSafe: true,
  },
  {
    title: "Warm Glow",
    artist: "CozyVibes",
    genre: "chillhop",
    mood: "cozy",
    tempo: "medium",
    instrument: "guitar",
    durationSec: 176,
    licenseType: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://chosic.com/free-music/cozyvibes-warm-glow/",
    sourcePlatform: "Chosic",
    tags: "warm,glow,cozy,guitar",
    isYoutubeSafe: true,
  },
  {
    title: "Lazy Sunday",
    artist: "Kevin MacLeod",
    genre: "lofi-chill",
    mood: "peaceful",
    tempo: "slow",
    instrument: "piano",
    durationSec: 185,
    licenseType: "CC-BY-3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://incompetech.com/music/royalty-free/?collection=27&search=Lazy+Sunday",
    sourcePlatform: "Incompetech",
    tags: "lazy,sunday,peaceful,relaxing",
    isYoutubeSafe: true,
  },
  {
    title: "Soft Focus",
    artist: "Kevin MacLeod",
    genre: "lofi-ambient",
    mood: "dreamy",
    tempo: "slow",
    instrument: "synth",
    durationSec: 240,
    licenseType: "CC-BY-3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://incompetech.com/music/royalty-free/?collection=27&search=Soft+Focus",
    sourcePlatform: "Incompetech",
    tags: "soft,dreamy,ambient,synth",
    isYoutubeSafe: true,
  },
  {
    title: "Slow Morning",
    artist: "Bensound",
    genre: "lofi-chill",
    mood: "calm",
    tempo: "slow",
    instrument: "piano",
    durationSec: 215,
    licenseType: "Custom",
    licenseUrl: "https://www.bensound.com/licensing",
    sourceUrl: "https://www.bensound.com/royalty-free-music/track/slow-morning",
    sourcePlatform: "Bensound",
    tags: "morning,calm,slow,piano",
    isYoutubeSafe: true,
  },
  {
    title: "Ukulele Dream",
    artist: "Bensound",
    genre: "chillhop",
    mood: "uplifting",
    tempo: "medium",
    instrument: "guitar",
    durationSec: 168,
    licenseType: "Custom",
    licenseUrl: "https://www.bensound.com/licensing",
    sourceUrl: "https://www.bensound.com/royalty-free-music/track/ukulele-dream",
    sourcePlatform: "Bensound",
    tags: "ukulele,happy,uplifting,acoustic",
    isYoutubeSafe: true,
  },
  {
    title: "Night Drive",
    artist: "SynthwaveDreams",
    genre: "vaporwave",
    mood: "nostalgic",
    tempo: "medium",
    instrument: "synth",
    durationSec: 298,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/synthwavedreams/night-drive",
    sourcePlatform: "SoundCloud",
    tags: "night,drive,synthwave,vaporwave",
    isYoutubeSafe: true,
  },
  {
    title: "Cloud Nine",
    artist: "DreamscapeAudio",
    genre: "dream-pop",
    mood: "dreamy",
    tempo: "slow",
    instrument: "synth",
    durationSec: 247,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/dreamscapeaudio/cloud-nine/",
    sourcePlatform: "FMA",
    tags: "clouds,dreamy,floating,ethereal",
    isYoutubeSafe: true,
  },
  {
    title: "Autumn Leaves Falling",
    artist: "JazzCat",
    genre: "lofi-jazz",
    mood: "melancholic",
    tempo: "slow",
    instrument: "sax",
    durationSec: 203,
    licenseType: "CC-BY-SA",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/jazzcat/autumn-leaves-falling/",
    sourcePlatform: "FMA",
    tags: "autumn,jazz,saxophone,leaves",
    isYoutubeSafe: true,
  },
  {
    title: "Chill Vibes Only",
    artist: "LofiBeatsOfficial",
    genre: "chillhop",
    mood: "calm",
    tempo: "medium",
    instrument: "mixed",
    durationSec: 192,
    licenseType: "Pixabay",
    licenseUrl: "https://pixabay.com/service/terms/",
    sourceUrl: "https://pixabay.com/music/lofi-beats-official-chill-vibes-only/",
    sourcePlatform: "Pixabay",
    tags: "chill,vibes,relaxing,beats",
    isYoutubeSafe: true,
  },
  {
    title: "Deep Focus",
    artist: "StudyBeats",
    genre: "lofi-study",
    mood: "focused",
    tempo: "medium",
    instrument: "piano",
    durationSec: 340,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/studybeats/deep-focus",
    sourcePlatform: "SoundCloud",
    tags: "focus,study,concentration,deep",
    isYoutubeSafe: true,
  },
  {
    title: "Moonlit Walk",
    artist: "AmbientWanderer",
    genre: "lofi-ambient",
    mood: "peaceful",
    tempo: "slow",
    instrument: "piano",
    durationSec: 275,
    licenseType: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://chosic.com/free-music/ambient-wanderer-moonlit-walk/",
    sourcePlatform: "Chosic",
    tags: "moon,night,walk,peaceful",
    isYoutubeSafe: true,
  },
  {
    title: "Sunset Boulevard",
    artist: "RetroWave",
    genre: "vaporwave",
    mood: "nostalgic",
    tempo: "slow",
    instrument: "synth",
    durationSec: 256,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/retrowave/sunset-boulevard/",
    sourcePlatform: "FMA",
    tags: "sunset,retro,vaporwave,mall",
    isYoutubeSafe: true,
  },
  {
    title: "Gentle Breeze",
    artist: "NatureSounds",
    genre: "lofi-ambient",
    mood: "peaceful",
    tempo: "slow",
    instrument: "flute",
    durationSec: 310,
    licenseType: "Pixabay",
    licenseUrl: "https://pixabay.com/service/terms/",
    sourceUrl: "https://pixabay.com/music/nature-sounds-gentle-breeze/",
    sourcePlatform: "Pixabay",
    tags: "breeze,nature,gentle,flute",
    isYoutubeSafe: true,
  },
  {
    title: "Late Night Jazz",
    artist: "SmoothOperator",
    genre: "lofi-jazz",
    mood: "romantic",
    tempo: "slow",
    instrument: "sax",
    durationSec: 228,
    licenseType: "CC-BY-3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://freemusicarchive.org/music/smoothoperator/late-night-jazz/",
    sourcePlatform: "FMA",
    tags: "jazz,late-night,romantic,sax",
    isYoutubeSafe: true,
  },
  {
    title: "Pixel Dreams",
    artist: "ChipTuneLofi",
    genre: "vaporwave",
    mood: "nostalgic",
    tempo: "medium",
    instrument: "synth",
    durationSec: 178,
    licenseType: "CC-BY-SA",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://soundcloud.com/chiptunelofi/pixel-dreams",
    sourcePlatform: "SoundCloud",
    tags: "pixel,retro,8-bit,nostalgia",
    isYoutubeSafe: true,
  },
  {
    title: "Ethereal Morning",
    artist: "DreamPopCollective",
    genre: "dream-pop",
    mood: "dreamy",
    tempo: "slow",
    instrument: "guitar",
    durationSec: 265,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/dreampop-collective/ethereal-morning/",
    sourcePlatform: "FMA",
    tags: "ethereal,morning,dreamy,guitar",
    isYoutubeSafe: true,
  },
  {
    title: "Lo-fi Haze",
    artist: "HazeBeats",
    genre: "lofi-hiphop",
    mood: "dreamy",
    tempo: "slow",
    instrument: "drums",
    durationSec: 195,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/hazebeats/lo-fi-haze",
    sourcePlatform: "SoundCloud",
    tags: "haze,dreamy,hip-hop,beats",
    isYoutubeSafe: true,
  },
  {
    title: "Quiet Storm",
    artist: "Mixkit Audio",
    genre: "downtempo",
    mood: "calm",
    tempo: "slow",
    instrument: "mixed",
    durationSec: 182,
    licenseType: "Pixabay",
    licenseUrl: "https://pixabay.com/service/terms/",
    sourceUrl: "https://mixkit.co/free-stock-music/quiet-storm/",
    sourcePlatform: "Mixkit",
    tags: "storm,quiet,downtempo,chill",
    isYoutubeSafe: true,
  },
  {
    title: "Bossa Nova Nights",
    artist: "LatinLofi",
    genre: "lofi-jazz",
    mood: "romantic",
    tempo: "medium",
    instrument: "guitar",
    durationSec: 234,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/latinlofi/bossa-nova-nights/",
    sourcePlatform: "FMA",
    tags: "bossa-nova,latin,romantic,guitar",
    isYoutubeSafe: true,
  },
  {
    title: "Space Drift",
    artist: "CosmicAmbience",
    genre: "ambient",
    mood: "dreamy",
    tempo: "slow",
    instrument: "synth",
    durationSec: 356,
    licenseType: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://chosic.com/free-music/cosmic-ambience-space-drift/",
    sourcePlatform: "Chosic",
    tags: "space,cosmic,drift,ambient",
    isYoutubeSafe: true,
  },
  {
    title: "Dusty Records",
    artist: "VinylCollector",
    genre: "lofi-hiphop",
    mood: "nostalgic",
    tempo: "medium",
    instrument: "drums",
    durationSec: 208,
    licenseType: "CC-BY-3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://freemusicarchive.org/music/vinylcollector/dusty-records/",
    sourcePlatform: "FMA",
    tags: "dusty,vinyl,records,hip-hop",
    isYoutubeSafe: true,
  },
  {
    title: "Ocean Waves",
    artist: "CoastalBeats",
    genre: "downtempo",
    mood: "peaceful",
    tempo: "slow",
    instrument: "synth",
    durationSec: 290,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/coastalbeats/ocean-waves",
    sourcePlatform: "SoundCloud",
    tags: "ocean,waves,coastal,peaceful",
    isYoutubeSafe: true,
  },
  {
    title: "Purple Sky",
    artist: "TwilightLofi",
    genre: "dream-pop",
    mood: "dreamy",
    tempo: "medium",
    instrument: "guitar",
    durationSec: 219,
    licenseType: "CC-BY-SA",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/twilightlofi/purple-sky/",
    sourcePlatform: "FMA",
    tags: "purple,twilight,sky,dreamy",
    isYoutubeSafe: true,
  },
  {
    title: "Fireplace Chats",
    artist: "CozyVibes",
    genre: "lofi-chill",
    mood: "cozy",
    tempo: "slow",
    instrument: "piano",
    durationSec: 245,
    licenseType: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://chosic.com/free-music/cozyvibes-fireplace-chats/",
    sourcePlatform: "Chosic",
    tags: "fireplace,cozy,warm,chats",
    isYoutubeSafe: true,
  },
  {
    title: "Urban Jungle",
    artist: "CityBeatMaker",
    genre: "chillhop",
    mood: "uplifting",
    tempo: "fast",
    instrument: "mixed",
    durationSec: 165,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/citybeatmaker/urban-jungle",
    sourcePlatform: "SoundCloud",
    tags: "urban,city,uplifting,beats",
    isYoutubeSafe: true,
  },
  {
    title: "Starlight Serenade",
    artist: "NightOwlBeats",
    genre: "lofi-chill",
    mood: "romantic",
    tempo: "slow",
    instrument: "violin",
    durationSec: 232,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/nightowlbeats/starlight-serenade",
    sourcePlatform: "SoundCloud",
    tags: "starlight,romantic,serenade,violin",
    isYoutubeSafe: true,
  },
  {
    title: "Morning Dew",
    artist: "FreshStartBeats",
    genre: "lofi-study",
    mood: "uplifting",
    tempo: "medium",
    instrument: "piano",
    durationSec: 175,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/freshstartbeats/morning-dew/",
    sourcePlatform: "FMA",
    tags: "morning,dew,fresh,uplifting",
    isYoutubeSafe: true,
  },
  {
    title: "Fading Memories",
    artist: "GhostlyEcho",
    genre: "lofi-ambient",
    mood: "sad",
    tempo: "slow",
    instrument: "piano",
    durationSec: 288,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/ghostlyecho/fading-memories/",
    sourcePlatform: "FMA",
    tags: "memories,fading,sad,echo",
    isYoutubeSafe: true,
  },
  {
    title: "Rooftop Sunset",
    artist: "SkylineBeats",
    genre: "chillhop",
    mood: "peaceful",
    tempo: "medium",
    instrument: "guitar",
    durationSec: 198,
    licenseType: "Pixabay",
    licenseUrl: "https://pixabay.com/service/terms/",
    sourceUrl: "https://pixabay.com/music/skyline-beats-rooftop-sunset/",
    sourcePlatform: "Pixabay",
    tags: "rooftop,sunset,skyline,guitar",
    isYoutubeSafe: true,
  },
  {
    title: "Raindrop Melody",
    artist: "PuddleBeats",
    genre: "lofi-hiphop",
    mood: "calm",
    tempo: "slow",
    instrument: "piano",
    durationSec: 215,
    licenseType: "CC-BY-3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://incompetech.com/music/royalty-free/?collection=27&search=Raindrop+Melody",
    sourcePlatform: "Incompetech",
    tags: "raindrop,melody,calm,piano",
    isYoutubeSafe: true,
  },
  {
    title: "Neon City",
    artist: "SynthwaveDreams",
    genre: "vaporwave",
    mood: "nostalgic",
    tempo: "medium",
    instrument: "synth",
    durationSec: 274,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/synthwavedreams/neon-city",
    sourcePlatform: "SoundCloud",
    tags: "neon,city,retro,synthwave",
    isYoutubeSafe: true,
  },
  {
    title: "Whispering Pines",
    artist: "ForestLofi",
    genre: "lofi-ambient",
    mood: "peaceful",
    tempo: "slow",
    instrument: "flute",
    durationSec: 302,
    licenseType: "CC-BY-SA",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/forestlofi/whispering-pines/",
    sourcePlatform: "FMA",
    tags: "forest,pines,whisper,flute",
    isYoutubeSafe: true,
  },
  {
    title: "Tokyo Drift Lofi",
    artist: "EasternWaves",
    genre: "lofi-hiphop",
    mood: "dreamy",
    tempo: "medium",
    instrument: "mixed",
    durationSec: 187,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/easternwaves/tokyo-drift-lofi",
    sourcePlatform: "SoundCloud",
    tags: "tokyo,japanese,drift,asian",
    isYoutubeSafe: true,
  },
  {
    title: "Blissful Ignorance",
    artist: "CloudWatcher",
    genre: "dream-pop",
    mood: "dreamy",
    tempo: "slow",
    instrument: "synth",
    durationSec: 258,
    licenseType: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://chosic.com/free-music/cloudwatcher-blissful-ignorance/",
    sourcePlatform: "Chosic",
    tags: "bliss,clouds,dreamy,synth",
    isYoutubeSafe: true,
  },
  {
    title: "Sunday Papers",
    artist: "MorningRitual",
    genre: "lofi-chill",
    mood: "cozy",
    tempo: "slow",
    instrument: "piano",
    durationSec: 195,
    licenseType: "Pixabay",
    licenseUrl: "https://pixabay.com/service/terms/",
    sourceUrl: "https://pixabay.com/music/morning-ritual-sunday-papers/",
    sourcePlatform: "Pixabay",
    tags: "sunday,papers,cozy,morning",
    isYoutubeSafe: true,
  },
  {
    title: "Gravity",
    artist: "FloatBeats",
    genre: "downtempo",
    mood: "calm",
    tempo: "slow",
    instrument: "synth",
    durationSec: 328,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/floatbeats/gravity/",
    sourcePlatform: "FMA",
    tags: "gravity,float,downtempo,calm",
    isYoutubeSafe: true,
  },
  {
    title: "Candlelit Evening",
    artist: "NightOwlBeats",
    genre: "lofi-jazz",
    mood: "romantic",
    tempo: "slow",
    instrument: "sax",
    durationSec: 241,
    licenseType: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl: "https://soundcloud.com/nightowlbeats/candlelit-evening",
    sourcePlatform: "SoundCloud",
    tags: "candle,evening,romantic,sax",
    isYoutubeSafe: true,
  },
  // --- Non-YouTube-safe tracks ---
  {
    title: "Midnight Echoes",
    artist: "DarkLoFi",
    genre: "lofi-hiphop",
    mood: "sad",
    tempo: "slow",
    instrument: "piano",
    durationSec: 220,
    licenseType: "CC-BY-NC",
    licenseUrl: "https://creativecommons.org/licenses/by-nc/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/darklofi/midnight-echoes/",
    sourcePlatform: "FMA",
    tags: "midnight,echo,sad,dark",
    notes: "CC-BY-NC license: Not safe for YouTube monetization. Non-commercial use only — cannot be used in monetized YouTube videos.",
    isYoutubeSafe: false,
  },
  {
    title: "Frozen in Time",
    artist: "GlitchHop",
    genre: "downtempo",
    mood: "melancholic",
    tempo: "slow",
    instrument: "synth",
    durationSec: 255,
    licenseType: "CC-BY-ND",
    licenseUrl: "https://creativecommons.org/licenses/by-nd/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/glitchhop/frozen-in-time/",
    sourcePlatform: "FMA",
    tags: "frozen,time,glitch,melancholy",
    notes: "CC-BY-ND license: No derivatives allowed. Cannot remix, edit, or alter this track for YouTube compilation videos.",
    isYoutubeSafe: false,
  },
  {
    title: "Shadow Dance",
    artist: "DarkAmbient",
    genre: "ambient",
    mood: "sad",
    tempo: "slow",
    instrument: "synth",
    durationSec: 340,
    licenseType: "CC-BY-NC-SA",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/darkambient/shadow-dance/",
    sourcePlatform: "FMA",
    tags: "shadow,dance,dark,ambient",
    notes: "CC-BY-NC-SA license: Non-commercial use only and share-alike required. Not safe for YouTube monetization.",
    isYoutubeSafe: false,
  },
  {
    title: "Broken Clock",
    artist: "TimeWarpBeats",
    genre: "vaporwave",
    mood: "melancholic",
    tempo: "medium",
    instrument: "mixed",
    durationSec: 190,
    licenseType: "CC-BY-NC-ND",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    sourceUrl: "https://soundcloud.com/timewarpbeats/broken-clock",
    sourcePlatform: "SoundCloud",
    tags: "broken,clock,time,melancholy",
    notes: "CC-BY-NC-ND license: Most restrictive — non-commercial, no derivatives. Cannot use in monetized content or remix for YouTube.",
    isYoutubeSafe: false,
  },
  {
    title: "Empty Room",
    artist: "MinimalistLofi",
    genre: "lofi-ambient",
    mood: "sad",
    tempo: "slow",
    instrument: "piano",
    durationSec: 275,
    licenseType: "CC-BY-NC",
    licenseUrl: "https://creativecommons.org/licenses/by-nc/4.0/",
    sourceUrl: "https://freemusicarchive.org/music/minimalistlofi/empty-room/",
    sourcePlatform: "FMA",
    tags: "empty,room,sad,minimal",
    notes: "CC-BY-NC license: Non-commercial only. Cannot be used in YouTube videos with monetization enabled.",
    isYoutubeSafe: false,
  },
]

async function main() {
  console.log("Seeding database...")

  // Clear existing data (order matters for foreign keys)
  await prisma.playlistTrack.deleteMany()
  await prisma.playlist.deleteMany()
  await prisma.track.deleteMany()

  // Insert all tracks in batches for PostgreSQL performance
  const batchSize = 10
  for (let i = 0; i < tracks.length; i += batchSize) {
    const batch = tracks.slice(i, i + batchSize)
    await prisma.track.createMany({ data: batch })
  }

  console.log(`Seeded ${tracks.length} tracks.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
